### ISSUE TITLE
Adding special days code

### ISSUE THREAD

**Issue by davidbuckleyni** [DamianAntonowicz/XamarinForms.CalendarControl#1]
Its very good but @DamianAntonowicz I had trouble in being able to bind to the box view required for the Day Cell when I did calendarDay.BackgroundColour nothing happened it didn't change the active colour of the cell in quesiton maybe if u made a cell color property would make my special day code easier/

**Comment by DamianAntonowicz** [comment]
Could you fork my repo and add your changes to it? It would help me investigate the problem

**Comment by davidbuckleyni** [comment]
Fork is here i might need to give you permissions

https://github.com/davidbuckleyni/XamarinForms.CalendarControl/tree/XFCM-0001-XamarinForms-CalendarControl-SpecialDays

If you look in XamarinForms.CalendarComponent\Components\Calendar.xaml.cs
I have code ShowSpecialDays which is a new property on the calendar control I took out the ios project only cause i dont have my mac setup to compile at present.

if you trace back from line
447 you will see what am trying to do also a sample app CalPage.xaml as well.

What I want to achieve is the full square in different colour based on the list special days from the control, if we get this one working I can do another one for BankHolidays which is important feature of most calendars. I noticed u didnt have uwp their or winui if their going into maui we would need winui

**Comment by DamianAntonowicz** [comment]
What you are trying to achieve can be done with current API of Calendar control. Please refer to method Calendar_OnDayUpdated in MainPage.xaml.cs (https://github.com/DamianAntonowicz/XamarinForms.CalendarControl/blob/main/XamarinForms.CalendarComponent/MainPage.xaml.cs), which shows how to update visual presentation of specific day.

**Comment by davidbuckleyni** [comment]
I was doing this from the approach of making it inbuilt

**Comment by DamianAntonowicz** [comment]
Could you try it again and provide source code? It will help me to check what is wrong

**Comment by davidbuckleyni** [comment]
Odd on day Calendar_OnDayUpdated is not being fired for me is it an event in the calendar properties i must set.

**Comment by DamianAntonowicz** [comment]
What do you mean by "an event in the calendar properties i must set."?

**Comment by DamianAntonowicz** [comment]
Closing issue due lack of activity.
